### ISSUE TITLE
Cannot Generate PDF with 149 pages or more

### ISSUE THREAD

**Issue by jwdepetro** [mikehaertl/phpwkhtmltopdf#78]
I am trying to generate a PDF with 150+ pages and cannot seem to get a PDF with 149 or more pages.

If I run this simple loop for 148 pages and will execute fine and return an inline PDF in a second or two.

for($i = 0; $i < 148; $i++){
    $pdf->addPage('Single HTML test line');  
}
if(!$pdf->send()){
    logToFile('Error generating PDF', $pdf->getError());
}

Now if I increase the 148 to anything higher the browser window will keep spinning and no PDF will ever come back.  I looked in my tmp directory where everything is generated and the file count is correct.  Not sure what makes 149+ pages different than 148.

**Comment by datoneperson** [comment]
I had the same problem. I'm using wkhtmltopdf version 0.12.2.1 on ubuntu/trusty64. I commented out those three lines and I was able to get 700 pages opposed to the 149 limit from before. The useExec workaround did not work for me.

**Comment by mikehaertl** [comment]
@datoneperson Are you sure about useExec? If that is on, the above lines are not executed at all. What happens if you enable `useExec`?

**Comment by mikehaertl** [comment]
@datoneperson @pmxjason @jwdepetro There are some interesting comments in the [proc_open()](http://php.net/manual/en/function.proc-open.php) manual:

http://php.net/manual/en/function.proc-open.php#97012
http://php.net/manual/en/function.proc-open.php#81317

Maybe you can give that a try? I think the second one sounds interesting.  So you could try to insert this line after https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L288:

```
stream_set_blocking($pipes[2], 0);
```

**Comment by datoneperson** [comment]
@mikehaertl I get "Command failed" when trying to do useExec. 

I uncommented those three lines and added the line below after 288 and it didn't work. 
```
stream_set_blocking($pipes[2], 0);
```

The first link actually worked for me. Replace the array in line 285. I was able to print 1800 pages.
```
0 => array('pipe', 'r'), // stdin
1 => array('pipe', 'w'), // stdout
2 => array('pipe', 'a') // stderr
```

**Comment by mikehaertl** [comment]
Ok, I've just released `2.0.3` version. The problems here are actually issues of https://github.com/mikehaertl/php-shellcommand. Thus I've removed the `composer.json` file from this project so you can now update the dependencies independently. 

@datoneperson @pmxjason @jwdepetro
So you could now try to update to the latest version. It should be `2.0.3` vor `mikehaertl/phpwkhtmltopdf` and `1.0.5` for `mikehaertl/php-shellcommand`.

@datoneperson Are you on windows? Because in the comment in the PHP manual mentions that this problem only exists on windows. So I'm not sure if it also fixes the issue for the others.

**Comment by mikehaertl** [comment]
I had to undo this change in https://github.com/mikehaertl/php-shellcommand again, as it broke error reporting on linux.

To really solve the issue I'd need to know:

 * Did `mikehaertl/php-shellcommand` version `1.0.5` solve the issue for everyone?
 * Is this a Windows-only problem?

**Comment by datoneperson** [comment]
I got 1.0.5 working on Windows. And I'm guessing the problem is only on Windows.

**Comment by mikehaertl** [comment]
@datoneperson Thanks a lot. I'd be glad if you could help me testing. It's very easy: Simply replace the file in `vendor/mikehaertl/php-shellcommand/src/Command.php` with this file here:

https://raw.githubusercontent.com/mikehaertl/php-shellcommand/master/src/Command.php

This should fix both now, Windows and Linux. 

As soon as you confirm this fix, I'll tag 1.0.7 release, so all these other issues should hopefully be gone then.

**Comment by mikehaertl** [comment]
Just released php-shellcommand 1.0.7 which should fix the issue for windows machines. Feel free to reopen, if the problem still exists.

**Comment by datoneperson** [comment]
Sorry, been away for two days. The fix, now on 1.0.7, works on Windows.

**Comment by mikehaertl** [comment]
Ok, great. So hopefully that's fixed now also for the OP. :)

**Comment by Arthi93** [comment]
Actually on Debian 9 this issue still exists and I'm not able to generate PDF with over 149 pages regardless of using 'useExec' option
